.MODEL SMALL
.DATA
	A DB 03h
	B DB 02h
	C DB 01H
.STACK
.CODE
MAIN:
	MOV AX, @DATA	;INICIALIZACIÓN
	MOV DS, AX
	XOR AX, AX		;LIMPIEZA
	MOV AL, A		;A+B = 5
	ADD AL, B
	ADD AL, 30h		;AGREGAR EL CARACTER IMPRIMIBLE
	MOV DL, AL		;IMPRIMIR
	MOV AH, 02h
	INT 21h
	MOV DL, 0Ah		;SALTO DE LÍNEA
	INT 21h
	MOV AL, A		;A-C = 2
	SUB AL, C
	ADD AL, 30h		;AGREGAR EL CARACTER IMPRIMIBLE
	MOV DL, AL		;IMPRIMIR
	INT 21h
	MOV DL, 0Ah		;SALTO DE LÍNEA
	INT 21h
	MOV AL, A		;A+B+2C = 7
	ADD AL, B
	ADD AL, C
	ADD AL, C
	ADD AL, 30h		;AGREGAR EL CARACTER IMPRIMIBLE
	MOV DL, AL		;IMPRIMIR
	INT 21h
	MOV DL, 0Ah		;SALTO DE LÍNEA
	INT 21h
	MOV AL, A		;A+B-C = 4
	ADD AL, B
	SUB AL, C
	ADD AL, 30h		;AGREGAR EL CARACTER IMPRIMIBLE
	MOV DL, AL		;IMPRIMIR
	INT 21h
	MOV AH, 4Ch		;FIN DE PROGRAMA
	INT 21h
END MAIN